services:
        - postgres:latest

variables:
        POSTGRES_DB: epracas_db
        POSTGRES_USER: epracas
        POSTGRES_PASSWORD: "epracas123"
        DATABASE_URL: "postgres://epracas:epracas123@postgres/epracas_db"

before_script:
        - apt-get install python3 python3-dev python3-pip libpq-dev
        - pip install -r requirements.txt
        - python manage.py migrate

test:
        script:
                - py.test --ds=epracas.settings -s --create-db
