# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-10 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def remove_arquivos_esteio(apps, schema_editor):
        GrupoGestor = apps.get_model('pracas', 'GrupoGestor')
        try:
            gg_esteio = GrupoGestor.objects.get(
                id_pub='5233ceb4-5ed9-4e61-a871-d1fd3a222925')
            gg_esteio.documento_constituicao = None
            gg_esteio.estatuto = None
            gg_esteio.save()
        except GrupoGestor.DoesNotExist:
            pass

    dependencies = [
        ('pracas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_arquivos_esteio, migrations.RunPython.noop),
    ]
