# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-12 15:00
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('pracas', '0002_apaga_arquivos_esteio'),
    ]

    operations = [
        UnaccentExtension()
    ]
