# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracas', '0004_auto_20181227_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praca',
            name='telefone1',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.AlterField(
            model_name='praca',
            name='telefone2',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone de Contato'),
        ),
    ]
