# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-16 11:35
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracas', '0005_auto_20190816_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupogestor',
            name='nomeacao',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_grupogestor_to, verbose_name='Nomeação do Grupo Gestor'),
        ),
        migrations.AddField(
            model_name='praca',
            name='regimento_interno',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_grupogestor_to, verbose_name='Regimento Interno da Praça'),
        ),
    ]
