# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 16:00
from __future__ import unicode_literals

import atividades.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import eventtools.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pracas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_pub', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Público')),
                ('titulo', models.CharField(max_length=140, verbose_name='Titulo do Evento')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa da Atividade')),
                ('faixa_etaria', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Crianças'), (2, 'Adolescentes'), (3, 'Jovens'), (4, 'Adultos'), (5, 'Idosos'), (6, 'Livre')], null=True), default=[], null=True, size=None)),
                ('espaco', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Cineteatro'), (2, 'Biblioteca'), (3, 'Laboratório Multimídia'), (4, 'Quadra'), (5, 'Sala Multiuso'), (6, 'CRAS'), (7, 'Pista de Skate'), (8, 'Areas Externas')], null=True), default=[], null=True, size=None)),
                ('tipo', models.IntegerField(choices=[(1, 'Apresentação'), (2, 'Atendimento'), (3, 'Comercialização de Produtos'), (4, 'Curso'), (5, 'Espetaculo'), (6, 'Exposição'), (7, 'Feira de Trocas'), (8, 'Oficina'), (9, 'Palestra'), (10, 'Reunião'), (11, 'Seminário'), (12, 'Show'), (13, 'Festas'), (14, 'Outros')], verbose_name='Categoria da Atividade')),
                ('publico', models.CharField(blank=True, choices=[(1, 'Egressos do Sistema Prisional'), (2, 'Famílias de presos do Sistema Carcerário'), (3, 'Jovens em medidas socioeducativas'), (4, 'Pessoas ou grupos vítimas de violência'), (5, 'Pessoas em sofrimento psíquico'), (6, 'População em situação de rua'), (7, 'Catadores de material reciclável'), (8, 'Atingidos por empreendimento de Infraestrutura'), (9, 'Imigrantes'), (10, 'Familias acampadas'), (11, 'Agricultures Familiares'), (12, 'Assentados da Reforma Agrária'), (13, 'Povos e Comunidades Tradicionais de Matriz Africana'), (14, 'Quilombolas'), (15, 'Indígenas'), (16, 'Extrativistas'), (17, 'Pescadores artesanais'), (18, 'Ribeirinhos'), (19, 'Sertanejos'), (20, 'Ciganos'), (21, 'População de Lésbicas, Gays, Bissexuais, Travestis, Transexuais e Transgêneros - LGBT'), (22, 'Mulheres'), (23, 'Pessoas com Deficiência'), (24, 'População negra'), (25, 'Estudantes'), (26, 'Grupos Artísticos e Culturais Independentes'), (27, 'Mestres, praticantes, brincantes e grupos das culturas populares, urbanas e rurais.')], max_length=2, null=True, verbose_name='Publico alvo da atividade')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horaria da Atividade')),
                ('publico_esperado', models.IntegerField(verbose_name='Publico Esperado para a Atividade')),
                ('territorio', models.IntegerField(blank=True, choices=[(1, 'Bairro da Praça CEU'), (2, 'Bairros do Entorno da Praça'), (3, 'Munícipio'), (4, 'Municipios do Entorno'), (5, 'Estado')], null=True, verbose_name='Qual é o espaço de abrangencia desta atividade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Atividade')),
                ('praca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='pracas.Praca')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_pub', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Público')),
                ('nome', models.CharField(max_length=200, verbose_name='Área de Atividade')),
                ('slug', models.SlugField(blank=True, max_length=400, verbose_name='Slug')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='atividades.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repeat', eventtools.models.ChoiceTextField(blank=True, default='')),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('frequency_type', models.CharField(choices=[('once', 'Apenas uma vez'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente'), ('yearly', 'Anualmente')], default='once', max_length=19)),
                ('weekday', models.CharField(blank=True, max_length=20, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia', to='atividades.Agenda')),
            ],
            options={
                'ordering': ('start', 'end'),
                'abstract': False,
            },
            bases=(models.Model, eventtools.models.OccurrenceMixin),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id_pub', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Público')),
                ('realizado', models.BooleanField(default=False, verbose_name='Evento Realizado com Sucesso')),
                ('publico_presente', models.IntegerField(blank=True, null=True, verbose_name='Publico presente a atividade')),
                ('pontos_positivos', models.TextField(blank=True, null=True, verbose_name='Pontos Positivos da Atividade')),
                ('pontos_negativos', models.TextField(blank=True, null=True, verbose_name='Pontos Negativos da Atividade')),
                ('data_de_ocorrencia', models.DateField(default=django.utils.timezone.now)),
                ('data_prevista', models.DateTimeField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='atividades.Agenda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioImagem',
            fields=[
                ('id_pub', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Público')),
                ('arquivo', models.FileField(upload_to=atividades.models.upload_image_to)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='atividades.Agenda')),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='atividades.Relatorio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
