# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 16:15
from __future__ import unicode_literals

#from atividades.models import Area
from django.db import migrations

areas = [
    { 'nome':"Artes Cênicas", 'slug':"1" },
    { 'nome':"Audiovisual", 'slug':"2" },
    { 'nome':"Música", 'slug':"3" },
    { 'nome':"Artes Visuais", 'slug':"4" },
    { 'nome':"Patrimônio Cultural", 'slug':"5" },
    { 'nome':"Livro, Leitura e Literatura", 'slug':"6" },
    { 'nome':"Esportes", 'slug':"7" },
    { 'nome':"Assistência Social", 'slug':"7" },
    { 'nome':"Saúde", 'slug':"9" },
    { 'nome':"Outros", 'slug':"10" },
    { 'nome':"Circo", 'slug':"101", 'parent_id':'1' },

]


def create_areas(apps, schema_editor):
    Area = apps.get_model('atividades', 'Area')

    for area in areas:
        area_db = Area(nome=area['nome'],slug=area['slug'])
        if('parent_id' in area):
            print("AAAAAAAAAAa")
        area_db.save()


class Migration(migrations.Migration):

    dependencies = [
         ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_areas),
    ]