# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 16:15
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

areas = [
    { 'nome':"Artes Cênicas", 'children':
    [
        { 'nome':"Circo",  },
        { 'nome':"Dança", },
        { 'nome':"Mímica", },
        { 'nome':"Ópera", },
        { 'nome':"Teatro",},
    ]
    },
    { 'nome':"Audiovisual", 'children':
    [
        { 'nome':"Preservação/Restauração da Memória Cinematográfica", },
        { 'nome':"Produção Cinematográfica", },
        { 'nome':"Produção Radiofônica", },
        { 'nome':"Produção Televisiva", },
        { 'nome':"Rádios/TVs Comunitárias", },
        { 'nome':"Exibição Cinematográfica", },
    ]
    },
    { 'nome':"Música", 'children': 
    [
        { 'nome':"Música Erudita", },
        { 'nome':"Música Instrumental", },
        { 'nome':"Música Popular", },
        { 'nome':"Orquestra", },
        { 'nome':"Música em Geral", },            
    ]
    },
    { 'nome':"Artes Visuais", 'children':
    [
        { 'nome':"Fotografia", },
        { 'nome':"Gráficas", },
        { 'nome':"Plásticas", },
    ]
    },
    { 'nome':"Patrimônio Cultural", 'children':
    [
        { 'nome':"Acervo", },
        { 'nome':"Afro Brasileira", },
        { 'nome':"Arqueológico", },
        { 'nome':"Arquitetônico", },
        { 'nome':"Artesanato", },
        { 'nome':"Ecológico", },
        { 'nome':"Folclore", },
        { 'nome':"Histórico", },
        { 'nome':"Indígena", },
        { 'nome':"Museu", },
    ]
    },
    { 'nome':"Livro, Leitura e Literatura", 'children':
    [
        { 'nome':"Edição de Livros e outros", },
        { 'nome':"Evento literário", },
        { 'nome':"Leitura", },
        { 'nome':"Contação de história", },
        { 'nome':"Sarau", },
        { 'nome':"Outros", },
    ]
    },
    { 'nome':"Esportes", 'children':
    [
        { 'nome':"Futebol", },
        { 'nome':"Vôlei", },
        { 'nome':"Basquete", },
        { 'nome':"Skate", },
        { 'nome':"Handebol", },
        { 'nome':"Futevôlei", },
        { 'nome':"Capoeira", },
        { 'nome':"Outros", },
    ]
    },
    { 'nome':"Assistência Social", },
    { 'nome':"Saúde", },
    { 'nome':"Outros", },
]


def create_areas(apps, schema_editor):
    Area = apps.get_model('atividades', 'Area')

    for area in areas:
        parent = Area(nome=area['nome'], slug=slugify(area['nome']))
        parent.save()
        if 'children' in area:
            for child in area['children']:
                area_child = Area(nome=child['nome'], parent=parent, slug=slugify("{}__{}".format(parent.nome, child['nome'])))
                area_child.save()
        


class Migration(migrations.Migration):

    dependencies = [
         ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_areas),
    ]