# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_insert-area-subarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.Area'),
        ),
    ]
