# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-15 19:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_agenda_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='faixa_etaria',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Crianças (0 a 12 anos)'), (2, 'Adolescentes (13 a 17 anos)'), (3, 'Jovens (18 a 29)'), (4, 'Adultos (30 a 59)'), (5, 'Idosos (60 anos ou mais)'), (6, 'Livre')], null=True), default=[], null=True, size=None),
        ),
    ]
