# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_pub', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Público')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verificado')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('family_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Sobrenome')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo')),
                ('given_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome preferido')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome')),
                ('picture', models.URLField(blank=True, null=True, verbose_name='Avatar')),
                ('profile_picture_url', models.URLField(blank=True, null=True, verbose_name='URL do Avatar')),
                ('surname', models.CharField(blank=True, max_length=80, null=True, verbose_name='Sobrenome')),
                ('sub', models.IntegerField(blank=True, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
