#coding: utf-8

PARCEIRO_RAMO_ATIVIDADE = (
    (1, "agricultura, pecuária, produção florestal, pesca e aqüicultura"),
    (2, "indústrias extrativas"),
    (3, "indústrias de transformação"),
    (4, "eletricidade e gás"),
    (5, "água, esgoto, atividades de gestão de resíduos e descontaminação"),
    (6, "construção"),
    (7, "comércio; reparação de veículos automotores e motocicletas"),
    (8, "transporte, armazenagem e correio"),
    (9, "alojamento e alimentação"),
    (10, "informação e comunicação"),
    (11, "atividades financeiras, de seguros e serviços relacionados"),
    (12, "atividades imobiliárias"),
    (13, "atividades profissionais, científicas e técnicas"),
    (14, "atividades administrativas e serviços complementares"),
    (15, "administração pública, defesa e seguridade social"),
    (16, "educação"),
    (17, "saúde humana e serviços sociais"),
    (18, "artes, cultura, esporte e recreação"),
    (19, "outras atividades de serviços"),
    (20, "serviços domésticos"),
    (21, "organismos internacionais e outras instituições extraterritoriais"),
)
